### ISSUE TITLE
How to enable CORS ?

### ISSUE THREAD

**Issue by vcardins** [paulvanbladel/aureliauth#1]
First, thanks for this great piece of code !!
I'm not a node.js expert and I'm started my node server in another port, however I'm getting 401 - http://screencast.com/t/aTYKPs5nZ. Could you advice how I could enable CORS? Or is there anything else that I'm missing ? I tried to add
```javascript
app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});
```
but it didn't work.

**Comment by vcardins** [comment]
Never mind, I used this lib: https://github.com/expressjs/cors and it worked fine. Again, Great job !!!

**Comment by paulvanbladel** [comment]
Hi Victor,
Thanks for the very first comment in this new github repository.
I'm glad you figured out yourself the cors problem.
Cheers
paul.
