### ISSUE TITLE
Send token

### ISSUE THREAD

**Issue by RWOverdijk** [paulvanbladel/aureliauth#5]
How can I send the token along with every request I make? The README says:

> The aurelia token will be sent automatically to your API when the user is authenticated.

However, AuthService.isAuthenticated() returns true, and the token is not sent along with my requests. Here's how I make my requests:

```javascript
this.api.createRequest('/user/me')
      .asGet()
      .send().then(response => {
        this.user = response;
      });
```

this.api is just HttpClient (aurelia-http-client).

**Comment by maxfrigge** [comment]
Having the same issue. How did you resolve it?

**Comment by maxfrigge** [comment]
Well I found a way to do it.

    import {inject} from 'aurelia-framework';
    import HttpClientConfig from 'paulvanbladel/aurelia-auth/app.httpClient.config'

    @inject(HttpClientConfig)
    export class App {
      constructor(httpClientConfig) {
        this.httpClientConfig = httpClientConfig;
      }

      activate() {
        this.httpClientConfig.configure();
      }
      
    }

Calling `httpClientConfig.configure()` sets up the http client to send the header. 

Is this the official way to do it or is there some sort of configuration/option to achieve this?

**Comment by paulvanbladel** [comment]
Indeed, that's how it's done in the sample app.
https://github.com/paulvanbladel/aurelia-auth-sample/blob/master/client/src/app.js


```javascript
import 'bootstrap';
import 'bootstrap/css/bootstrap.css!';

import {inject} from 'aurelia-framework';
import {Router} from 'aurelia-router';
import AppRouterConfig from 'app.router.config';
import HttpClientConfig from 'aurelia-auth/app.httpClient.config';
@inject(Router,HttpClientConfig,AppRouterConfig )
export class App {

  constructor(router, httpClientConfig, appRouterConfig){
    this.router = router;
    this.httpClientConfig = httpClientConfig;
    this.appRouterConfig = appRouterConfig;
  }
  
  activate(){
    
    this.httpClientConfig.configure();
    this.appRouterConfig.configure();
  }
}
```
