### ISSUE TITLE
Proof integration

### ISSUE THREAD

**Issue by kristianmandrup** [paulvanbladel/aureliauth#8]
Suggestion: Would be nice if your plugin could also integrate with Proof authentication https://github.com/undercase/proof

**Comment by paulvanbladel** [comment]
Great suggestion, but I'm not familiar with rails as backend.

**Comment by kristianmandrup** [comment]
Just ask the author how you can contribute with an Adapter ;) Proof simply exposes a REST API that your adapter interacts with, similar to OAuth etc. 

"To help out, either contribute to this repository, or write adapters for popular client-side libraries, such as Ember, Angular, and React."

**Comment by paulvanbladel** [comment]
Happy to receive a PR for this Kristian :)
